# -*- coding: utf-8 -*-
"""Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sttHcH54JjiPuGhEl3F7JRlrUFEIJW-V
"""

# ===========================================
# Assignment 1: Dictionaries Practice
# ===========================================

# 1️⃣ Roll Numbers Dictionary
rollnumbers= {
    "001": "Ali",
    "002": "Usama",
    "003": "Kamran",
    "004": "Hassan",
    "005": "shan",
    "006": "Bilal",
    "007": "Umer",
    "008": "Amir",
    "009": "Asif",
    "010": "imran"
}

# 2️⃣ NamesNames Dictionary
names = {
    "001": "Ali",
    "002": "Usama",
    "003": "Kamran",
    "004": "Hassan",
    "005": "shan",
    "006": "Bilal",
    "007": "Umer",
    "008": "Amir",
    "009": "Asif",
    "010": "imran"
}

# 3️⃣ Marks Dictionary
marks = {
    "001": 45,
    "002": 39,
    "003": 48,
    "004": 41,
    "005": 44,
    "006": 36,
    "007": 50,
    "008": 42,
    "009": 47,
    "010": 38
}


roll = "010"
print(f"Name: {names[roll]}, Marks: {marks[roll]}")





