# -*- coding: utf-8 -*-
"""login_system_colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10tf_dI5UlPc_WiXC2K5BjhW9xX6GdxnO

# Login System using Nested If-Else
This notebook demonstrates a simple Python login system using nested if-else conditions.
"""

# Simple user login system using nested if-else

# Step 1: Take username and password as input
username = input("Enter your username: ")
password = input("Enter your password: ")

# Step 2: Check username first
if username == "student123":
    # Step 3: Check password if username matches
    if password == "python789":
        print("Login successful! Welcome, student123.")
    else:
        print("Incorrect password. Please try again.")
elif username == "teacher":
    if password == "teach2025":
        print("Login successful! Welcome, teacher.")
    else:
        print("Wrong password for teacher account.")
else:
    print("Username not found. Please register first.")

"""✅ **Instructions:**
1. Run the cell above.
2. Enter a username and password when prompted.
3. Try different combinations:
- Username: `student123`, Password: `python789`
- Username: `teacher`, Password: `teach2025`
- Any other username → 'Username not found' message.
"""